// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo2TU3IPA_OSUiATr6pwUrLudf_L8x3t8',
    appId: '1:851798078457:web:1d2b6fa4646af007514328',
    messagingSenderId: '851798078457',
    projectId: 'pfe17-18cc1',
    authDomain: 'pfe17-18cc1.firebaseapp.com',
    storageBucket: 'pfe17-18cc1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQYG0RIh7jjUjizMpwxVjUCaUW1BeaAGg',
    appId: '1:851798078457:android:926a1ef51d9cad1f514328',
    messagingSenderId: '851798078457',
    projectId: 'pfe17-18cc1',
    storageBucket: 'pfe17-18cc1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxUL38Nz1BJiNhLWPfGQvUK5XIUIKSvIM',
    appId: '1:851798078457:ios:cfd591a57129c685514328',
    messagingSenderId: '851798078457',
    projectId: 'pfe17-18cc1',
    storageBucket: 'pfe17-18cc1.appspot.com',
    iosBundleId: 'com.example.pfe1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxUL38Nz1BJiNhLWPfGQvUK5XIUIKSvIM',
    appId: '1:851798078457:ios:b804d47491a45168514328',
    messagingSenderId: '851798078457',
    projectId: 'pfe17-18cc1',
    storageBucket: 'pfe17-18cc1.appspot.com',
    iosBundleId: 'com.example.pfe1.RunnerTests',
  );
}
